DROP TABLE IF EXISTS schedules;
CREATE TABLE IF NOT EXISTS  schedules(
 id SERIAL PRIMARY KEY,
 user_id INTEGER NOT NULL,
 day INTEGER NOT NULL,
 start_at TIME NOT NULL,
 end_at TIME NOT NUll 
);

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS  users(
 id SERIAL PRIMARY KEY,
 firstname VARCHAR(60) NOT NULL,
 lastname VARCHAR(60) NOT NULL,
 email VARCHAR NOT NULL,
 password VARCHAR NOT NUll 
);